# Generated by Django 5.0.3 on 2024-03-21 04:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('total_expenses', models.IntegerField(default=0)),
                ('pincode', models.IntegerField(null=True)),
                ('gmail', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=55)),
                ('app_password', models.CharField(max_length=50)),
                ('number_of_expenses', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('allowedexpense', models.IntegerField(default=0)),
                ('monthlybudget', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user_status',
            },
        ),
        migrations.CreateModel(
            name='MailExpense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField()),
                ('item', models.TextField()),
                ('category', models.TextField()),
                ('date_of_purchase', models.DateTimeField()),
                ('platform', models.TextField(default='self')),
                ('status', models.TextField()),
                ('order_id', models.TextField()),
                ('feedback', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.userstatus')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email_id', models.CharField(default='', max_length=255)),
                ('sender', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.userstatus')),
            ],
            options={
                'db_table': 'expense',
            },
        ),
    ]
