# Generated by Django 5.0.3 on 2024-03-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MailExpense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField()),
                ('item', models.TextField()),
                ('category', models.TextField()),
                ('date_of_purchase', models.DateTimeField()),
                ('platform', models.TextField(default='self')),
                ('status', models.TextField()),
                ('order_id', models.TextField()),
                ('feedback', models.TextField()),
            ],
        ),
    ]
