# Generated by Django 5.0.3 on 2024-03-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_email_mailexpense'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('total_expenses', models.IntegerField(default=0)),
                ('number_of_expenses', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('allowedexpense', models.IntegerField(default=0)),
                ('monthlybudget', models.IntegerField(default=0)),
                ('pincode', models.IntegerField(null=True)),
                ('gmail', models.CharField(max_length=50)),
                ('app_password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'user_status',
            },
        ),
        migrations.AlterModelTable(
            name='email',
            table='expense',
        ),
    ]
